apiVersion: v1
kind: Service
metadata:
  name: svc-goodfood-product-postech-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
  selector:
    app: goodfood-product-postech